"""
Field Coverage Matrix for Phase 1 Gatekeeper.
Source of truth for field ownership, confidence floor, and reporting basis requirements.
Strictly maps to Phase1-WebApp-Implementation-Plan.md §3 and Phase1-PhaseC-Scraper-Implementation-Plan.md §2.
"""

from typing import Any, Dict

FIELD_COVERAGE_MATRIX: Dict[str, Dict[str, Any]] = {
    # Check 1 — Auditor & Regulator
    "audit_opinion": {
        "check": 1,
        "source": "AR -> Auditor's Report -> Opinion paragraph",
        "owner": "PDF tier 1 (D)",
        "owner_phase": "D",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "auditor_resigned_mid_tenure_last_3y": {
        "check": 1,
        "source": "AR + BSE/NSE Reg-30 announcements",
        "owner": "PDF tier 1 (D) + BSE/NSE adapters (F)",
        "owner_phase": "D/F",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "regulatory_action": {
        "check": 1,
        "source": "SEBI enforcement archive + press scan",
        "owner": "SEBI adapter (F)",
        "owner_phase": "F",
        "basis_required": False,
        "confidence_floor": "MANUAL",
    },
    "legal_fees": {
        "check": 1,
        "source": "AR -> Notes -> Other Expenses -> Legal & professional charges",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "audit_fees": {
        "check": 1,
        "source": "AR -> Notes -> Payment to auditors",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "legal_fees_prior_year": {
        "check": 1,
        "source": "Comparative column of note / prior-FY AR",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    # Check 2 — Promoter Pledge
    "govt_shareholding_pct": {
        "check": 2,
        "source": "Screener shareholding pattern (Govt row); BSE Reg-31 cross-check",
        "owner": "Screener (C), BSE (F)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "promoter_holding_pct_of_company": {
        "check": 2,
        "source": "Screener shareholding pattern",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "pledged_pct_of_promoter_holding": {
        "check": 2,
        "source": "Screener quarterly pledge; BSE Reg-31 cross-check",
        "owner": "Screener (C), BSE (F)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "pledged_pct_history_last_4q": {
        "check": 2,
        "source": "Screener trailing 4-8 quarters",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "pledged_pct_of_total_shares": {
        "check": 2,
        "source": "BSE Reg-31 if reported, else derived per §2c",
        "owner": "Screener/BSE (C/F), else derivation",
        "owner_phase": "Engine",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    # Check 3 — Related Party
    "rpt_sales_plus_purchases": {
        "check": 3,
        "source": "AR -> Notes -> Related Party Transactions (sales + purchases)",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "revenue": {
        "check": 3,
        "source": "AR -> Statement of P&L -> Revenue from operations",
        "owner": "PDF tier 2 (D), Screener cross-check (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "unusual_affiliate_dealings": {
        "check": 3,
        "source": "AR RPT note narrative + loans/advances to affiliates",
        "owner": "Review queue by default (E)",
        "owner_phase": "E",
        "basis_required": False,
        "confidence_floor": "MANUAL",
    },
    # Check 4 — Contingent Liabilities
    "contingent_liabilities": {
        "check": 4,
        "source": "AR -> Notes -> Contingent Liabilities and Commitments",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "net_worth": {
        "check": 4,
        "source": "AR -> Balance Sheet -> Total Equity / Shareholders' funds",
        "owner": "PDF tier 2 (D), Screener cross-check (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    # Check 5 — Cash Conversion
    "cfo_last_5y": {
        "check": 5,
        "source": "Screener Cash Flow -> Cash from Operating Activity, 5 FYs",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "HIGH",
    },
    "pat_last_5y": {
        "check": 5,
        "source": "Screener P&L -> Net Profit, 5 FYs",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "HIGH",
    },
    # Check 6 — Executive Stability
    "cfo_changes_last_3y": {
        "check": 6,
        "source": "AR Board's report KMP changes + BSE/NSE Reg-30 announcements",
        "owner": "PDF tier 1 (D) + BSE/NSE (F)",
        "owner_phase": "D/F",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "restatement_of_past_accounts": {
        "check": 6,
        "source": "AR -> prior-period-error / restatement note & auditor's EoM",
        "owner": "PDF tier 1 (D)",
        "owner_phase": "D",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    # Structural fields (§3.2)
    "years_of_track_record_available": {
        "check": None,
        "source": "Screener + BSE listing date & financial count",
        "owner": "Screener + BSE (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "data_basis": {
        "check": None,
        "source": "Run configuration / declared basis",
        "owner": "Orchestrator (C)",
        "owner_phase": "Orchestrator",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "company_type": {
        "check": None,
        "source": "Derived by the Decision Engine",
        "owner": "Engine",
        "owner_phase": "Engine",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "as_of_date": {
        "check": None,
        "source": "Job parameters",
        "owner": "Orchestrator",
        "owner_phase": "Orchestrator",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "ticker": {
        "check": None,
        "source": "Job parameters",
        "owner": "Orchestrator",
        "owner_phase": "Orchestrator",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "provenance": {
        "check": None,
        "source": "FieldProvenance map container",
        "owner": "Acquisition layer / Orchestrator",
        "owner_phase": "Acquisition",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
}
