"""
Field Coverage Matrix for Phase 1 Gatekeeper.
Source of truth for field ownership, confidence floor, and reporting basis requirements.
Strictly maps to Phase1-WebApp-Implementation-Plan.md §3 and Phase1-PhaseC-Scraper-Implementation-Plan.md §2.
"""

from typing import Any, Dict

FIELD_COVERAGE_MATRIX: Dict[str, Dict[str, Any]] = {
    # Check 1 — Auditor & Regulator
    "audit_opinion": {
        "check": 1,
        "source": "AR -> Auditor's Report -> Opinion paragraph",
        "owner": "PDF tier 1 (D)",
        "owner_phase": "D",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "auditor_resigned_mid_tenure_last_3y": {
        "check": 1,
        "source": "AR -> Auditor's Report CARO clause 3(xviii); BSE/NSE Reg-30 announcements post-date the AR",
        "owner": "PDF tier 1 (D) + BSE/NSE adapters (F, not yet implemented)",
        "owner_phase": "D/F",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "regulatory_action": {
        "check": 1,
        "source": "SEBI enforcement archive (primary, no adapter yet — see Rules §8.4-A); "
                   "AR Board's Report / Secretarial Audit annexure (PDF fallback per §8.4-A)",
        "owner": "SEBI adapter (F, not yet implemented); PDF tier 1 fallback (D)",
        "owner_phase": "D/F",
        "basis_required": False,
        # Rev — a MEDIUM-confidence AR-sourced "no action found" fallback is
        # the exact §8.4-A pattern (tag MEDIUM, don't suppress); a positive
        # hit is tagged LOW by the extractor itself so it never clears this
        # floor and always lands in manual review regardless.
        "confidence_floor": "MEDIUM",
    },
    "legal_fees": {
        "check": 1,
        "source": "AR -> Notes -> Other Expenses -> Legal & professional charges",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "audit_fees": {
        "check": 1,
        "source": "AR -> Notes -> Payment to auditors",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "legal_fees_prior_year": {
        "check": 1,
        "source": "Comparative column of note / prior-FY AR",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "industry_sector": {
        "check": 1,
        "source": "Screener.in company header (NSE/BSE sector tag), Rules §8.4-E",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "legal_fee_surge_explained": {
        "check": 1,
        "source": "Contingent Liabilities note, Board's Report, or news scan, Rules §8.4-E step 4",
        "owner": "Review queue by default (E)",
        "owner_phase": "E",
        "basis_required": False,
        "confidence_floor": "MANUAL",
    },
    # Check 2 — Promoter Pledge
    "govt_shareholding_pct": {
        "check": 2,
        "source": "Screener shareholding pattern (Govt row); BSE Reg-31 cross-check",
        "owner": "Screener (C), BSE (F)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "promoter_holding_pct_of_company": {
        "check": 2,
        "source": "Screener shareholding pattern",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "pledged_pct_of_promoter_holding": {
        "check": 2,
        "source": "Screener quarterly pledge; BSE Reg-31 cross-check",
        "owner": "Screener (C), BSE (F)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "pledged_pct_history_last_4q": {
        "check": 2,
        "source": "Screener trailing 4-8 quarters",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "pledged_pct_of_total_shares": {
        "check": 2,
        "source": "BSE Reg-31 if reported, else derived per §2c",
        "owner": "Screener/BSE (C/F), else derivation",
        "owner_phase": "Engine",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "pledged_pct_history_retrieval_tier": {
        "check": 2,
        "source": "Structural — PRIMARY if trailing-4q series per Rules §8.4-B, FALLBACK if inferred",
        "owner": "Screener/BSE (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    # Check 3 — Related Party
    "rpt_sales_plus_purchases": {
        "check": 3,
        "source": "AR -> Notes -> Related Party Transactions (sales + purchases)",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "revenue": {
        "check": 3,
        "source": "AR -> Statement of P&L -> Revenue from operations",
        "owner": "PDF tier 2 (D), Screener cross-check (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "unusual_affiliate_dealings": {
        "check": 3,
        "source": "AR RPT note narrative + loans/advances to affiliates",
        "owner": "Review queue by default (E)",
        "owner_phase": "E",
        "basis_required": False,
        "confidence_floor": "MANUAL",
    },
    # Check 4 — Contingent Liabilities
    "contingent_liabilities": {
        "check": 4,
        "source": "AR -> Notes -> Contingent Liabilities and Commitments",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "net_worth": {
        "check": 4,
        "source": "AR -> Balance Sheet -> Total Equity / Shareholders' funds",
        "owner": "PDF tier 2 (D), Screener cross-check (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "litigation_claims_exposure": {
        "check": 4,
        "source": "AR -> Contingent Liabilities note -> litigation/claims sub-categories, Rules §8.4-F",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "routine_guarantee_exposure": {
        "check": 4,
        "source": "AR -> Contingent Liabilities note -> routine guarantee/LC/bills-discounted sub-categories, Rules §8.4-F",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "contingent_liabilities_breakdown_available": {
        "check": 4,
        "source": "Derived — true only if the Schedule III sub-categories were extracted separately",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    # Check 5 — Cash Conversion
    "cfo_last_5y": {
        "check": 5,
        "source": "Screener Cash Flow -> Cash from Operating Activity, 5 FYs",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "HIGH",
    },
    "pat_last_5y": {
        "check": 5,
        "source": "Screener P&L -> Net Profit, 5 FYs",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "HIGH",
    },
    "working_capital_cycle_tier": {
        "check": 5,
        "source": "Screener.in company header (NSE/BSE sector tag), Rules §8.4-G",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "revenue_last_5y": {
        "check": 5,
        "source": "Screener 5-yr view / AR, same FY alignment as cfo_last_5y/pat_last_5y",
        "owner": "Screener (C)",
        "owner_phase": "C",
        "basis_required": True,
        "confidence_floor": "HIGH",
    },
    "cumulative_working_capital_change_5y": {
        "check": 5,
        "source": "AR Cash Flow Statement -> 'Changes in working capital' subtotal, summed 5 FYs, Rules §8.4-H",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "liquid_cushion_first_year": {
        "check": 5,
        "source": "AR Balance Sheet -> cash + bank deposits + current investments, first year of window",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "liquid_cushion_last_year": {
        "check": 5,
        "source": "AR Balance Sheet -> cash + bank deposits + current investments, last year of window",
        "owner": "PDF tier 2/3 (D)",
        "owner_phase": "D",
        "basis_required": True,
        "confidence_floor": "MEDIUM",
    },
    "years_5y_series_gap_checked": {
        "check": 5,
        "source": "Structural — true only if the §8.4-C completeness sub-step was attempted",
        "owner": "Screener/Orchestrator (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    # Check 6 — Executive Stability
    "cfo_changes_last_3y": {
        "check": 6,
        "source": "AR Board's report KMP changes (current FY only); BSE/NSE Reg-30 announcements post-date the AR",
        "owner": "PDF tier 1 (D) + BSE/NSE adapters (F, not yet implemented)",
        "owner_phase": "D/F",
        "basis_required": False,
        # A change-log-derived count is inferential, not a stated figure —
        # tagged MEDIUM by the extractor, so it correctly routes to review
        # rather than being silently accepted as the full 3-year answer.
        "confidence_floor": "MEDIUM",
    },
    "restatement_of_past_accounts": {
        "check": 6,
        "source": "AR -> prior-period-error / restatement note & auditor's EoM, Rules §8.4-D",
        "owner": "PDF tier 1 (D)",
        "owner_phase": "D",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "restatement_search_retrieval_tier": {
        "check": 6,
        "source": "Structural — PRIMARY if sourced per Rules §8.4-D, FALLBACK if only a general keyword scan",
        "owner": "PDF tier 1 (D)",
        "owner_phase": "D",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "restatement_esg_only_excluded": {
        "check": 6,
        "source": "Rules §8.4-D disambiguation — true if a restatement-shaped mention was found and confirmed ESG/BRSR-only",
        "owner": "PDF tier 1 (D)",
        "owner_phase": "D",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    # Structural fields (§3.2)
    "years_of_track_record_available": {
        "check": None,
        "source": "Screener + BSE listing date & financial count",
        "owner": "Screener + BSE (C)",
        "owner_phase": "C",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
    "data_basis": {
        "check": None,
        "source": "Run configuration / declared basis",
        "owner": "Orchestrator (C)",
        "owner_phase": "Orchestrator",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "company_type": {
        "check": None,
        "source": "Derived by the Decision Engine",
        "owner": "Engine",
        "owner_phase": "Engine",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "as_of_date": {
        "check": None,
        "source": "Job parameters",
        "owner": "Orchestrator",
        "owner_phase": "Orchestrator",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "ticker": {
        "check": None,
        "source": "Job parameters",
        "owner": "Orchestrator",
        "owner_phase": "Orchestrator",
        "basis_required": False,
        "confidence_floor": "DERIVED",
    },
    "provenance": {
        "check": None,
        "source": "FieldProvenance map container",
        "owner": "Acquisition layer / Orchestrator",
        "owner_phase": "Acquisition",
        "basis_required": False,
        "confidence_floor": "HIGH",
    },
}
